name: Build Docker image

on: [ push ]

jobs:
    build-ubuntu1804-image:
        name: Build Docker Image for building Ezra Project on Ubuntu 18.04
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Ubuntu1804_Dockerfile
              image: toklein/ezra-ubuntu-1804
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-ubuntu1910-image:
        name: Build Docker Image for building Ezra Project on Ubuntu 19.10
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Ubuntu1910_Dockerfile
              image: toklein/ezra-ubuntu-1910
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-mint18-image:
        name: Build Docker Image for building Ezra Project on Mint 18
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Mint18_Dockerfile
              image: toklein/ezra-mint-18
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-mint19-image:
        name: Build Docker Image for building Ezra Project on Mint 19
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Mint19_Dockerfile
              image: toklein/ezra-mint-19
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-buster-image:
        name: Build Docker Image for building Ezra Project on Debian 10 Buster
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Buster_Dockerfile
              image: toklein/ezra-buster
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

