name: Build Docker image

on: [ push ]

jobs:
    build-ubuntu2004-image:
      name: Build Docker Image for building Ezra Bible App on Ubuntu 20.04
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        name: Check out

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
            dockerfile: docker/Ubuntu2004_Dockerfile
            image: toklein/ezra-ubuntu-2004
            tag: latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    build-ubuntu2204-image:
      name: Build Docker Image for building Ezra Bible App on Ubuntu 22.04
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        name: Check out

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
            dockerfile: docker/Ubuntu2204_Dockerfile
            image: toklein/ezra-ubuntu-2204
            tag: latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    build-ubuntu2404-image:
      name: Build Docker Image for building Ezra Bible App on Ubuntu 24.04
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        name: Check out

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
            dockerfile: docker/Ubuntu2404_Dockerfile
            image: toklein/ezra-ubuntu-2404
            tag: latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    build-mint21-image:
        name: Build Docker Image for building Ezra Bible App on Mint 21
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Mint21_Dockerfile
              image: toklein/ezra-mint-21
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-buster-image:
        name: Build Docker Image for building Ezra Bible App on Debian 10 Buster
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Buster_Dockerfile
              image: toklein/ezra-buster
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-bullseye-image:
        name: Build Docker Image for building Ezra Bible App on Debian 11 Bullseye
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/BullsEye_Dockerfile
              image: toklein/ezra-bullseye
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-bookworm-image:
        name: Build Docker Image for building Ezra Bible App on Debian 12 Bookworm
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Debian12_Bookworm_Dockerfile
              image: toklein/ezra-bookworm
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

#    build-centos8-image:
#        name: Build Docker Image for building Ezra Bible App on CentOS 8
#        runs-on: ubuntu-latest
#        steps:
#        - uses: actions/checkout@v1
#          name: Check out
#
#        - uses: mr-smithers-excellent/docker-build-push@v3
#          name: Build & push Docker image
#          with:
#              dockerfile: docker/CentOS8_Dockerfile
#              image: toklein/ezra-centos8
#              tag: latest
#              registry: docker.io
#              username: ${{ secrets.DOCKER_USERNAME }}
#              password: ${{ secrets.DOCKER_PASSWORD }}

    build-fedora31-image:
        name: Build Docker Image for building Ezra Bible App on Fedora 31
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Fedora31_Dockerfile
              image: toklein/ezra-fedora31
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-fedora32-image:
        name: Build Docker Image for building Ezra Bible App on Fedora 32
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Fedora32_Dockerfile
              image: toklein/ezra-fedora32
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-fedora33-image:
        name: Build Docker Image for building Ezra Bible App on Fedora 33
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Fedora33_Dockerfile
              image: toklein/ezra-fedora33
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-fedora35-image:
        name: Build Docker Image for building Ezra Bible App on Fedora 35
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Fedora35_Dockerfile
              image: toklein/ezra-fedora35
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-fedora37-image:
        name: Build Docker Image for building Ezra Bible App on Fedora 37
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/Fedora37_Dockerfile
              image: toklein/ezra-fedora37
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    build-opensuseleap-image:
        name: Build Docker Image for building Ezra Bible App on OpenSuse Leap
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
              dockerfile: docker/OpenSuseLeap_Dockerfile
              image: toklein/ezra-opensuse-leap-15.2
              tag: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

